
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calculator(object):



    def calculate(self,x):
        self.lineEdit.clear()
        def calci():

            self.lineEdit.setText(self.lineEdit.text()+ x)
        return calci
    def equate(self):
        self.lineEdit.setText(str(eval(self.lineEdit.text())))


    # Button Methods
    def setupUi(self, calculator):
        calculator.setObjectName("calculator")
        calculator.resize(442, 499)
        calculator.setMinimumSize(QtCore.QSize(442, 499))
        calculator.setMaximumSize(QtCore.QSize(442, 499))
        self.lineEdit = QtWidgets.QLineEdit(calculator)
        self.lineEdit.setGeometry(QtCore.QRect(10, 20, 421, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(calculator)
        self.pushButton.setGeometry(QtCore.QRect(10, 140, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(calculator)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 140, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(calculator)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 140, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(calculator)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 140, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(calculator)
        self.pushButton_5.setGeometry(QtCore.QRect(340, 230, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(calculator)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 230, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(calculator)
        self.pushButton_7.setGeometry(QtCore.QRect(120, 230, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(calculator)
        self.pushButton_8.setGeometry(QtCore.QRect(230, 230, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(calculator)
        self.pushButton_9.setGeometry(QtCore.QRect(340, 320, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(calculator)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 320, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(calculator)
        self.pushButton_11.setGeometry(QtCore.QRect(120, 320, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(calculator)
        self.pushButton_12.setGeometry(QtCore.QRect(230, 320, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(calculator)
        self.pushButton_13.setGeometry(QtCore.QRect(340, 410, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setAutoFillBackground(True)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(calculator)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 410, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(calculator)
        self.pushButton_15.setGeometry(QtCore.QRect(120, 410, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(calculator)
        self.pushButton_16.setGeometry(QtCore.QRect(230, 410, 93, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        #############################################################
        self.pushButton_16.clicked.connect(self.calculate('1'))
        self.pushButton_15.clicked.connect(self.calculate('2'))
        self.pushButton_14.clicked.connect(self.calculate('3'))
        self.pushButton_13.clicked.connect(self.equate)
        self.pushButton_12.clicked.connect(self.calculate('4'))
        self.pushButton_11.clicked.connect(self.calculate('5'))
        self.pushButton_10.clicked.connect(self.calculate('6'))
        # self.pushButton_9.clicked.connect(self.calculate('1'))
        self.pushButton_8.clicked.connect(self.calculate('7'))
        self.pushButton_7.clicked.connect(self.calculate('8'))
        self.pushButton_6.clicked.connect(self.calculate('9'))
        self.pushButton_5.clicked.connect(self.calculate('%'))
        self.pushButton_4.clicked.connect(self.calculate('/'))
        self.pushButton_3.clicked.connect(self.calculate('*'))
        self.pushButton_2.clicked.connect(self.calculate('-'))
        self.pushButton.clicked.connect(self.calculate('+'))
        self.pushButton_9.clicked.connect(self.lineEdit.clear)



        self.retranslateUi(calculator)
        QtCore.QMetaObject.connectSlotsByName(calculator)


    def retranslateUi(self, calculator):
        _translate = QtCore.QCoreApplication.translate
        calculator.setWindowTitle(_translate("calculator", "calculator"))
        self.pushButton.setText(_translate("calculator", "+"))
        self.pushButton_2.setText(_translate("calculator", "-"))
        self.pushButton_3.setText(_translate("calculator", "x"))
        self.pushButton_4.setText(_translate("calculator", "/"))
        self.pushButton_5.setText(_translate("calculator", "%"))
        self.pushButton_6.setText(_translate("calculator", "9"))
        self.pushButton_7.setText(_translate("calculator", "8"))
        self.pushButton_8.setText(_translate("calculator", "7"))
        self.pushButton_9.setText(_translate("calculator", "Clear"))
        self.pushButton_10.setText(_translate("calculator", "6"))
        self.pushButton_11.setText(_translate("calculator", "5"))
        self.pushButton_12.setText(_translate("calculator", "4"))
        self.pushButton_13.setText(_translate("calculator", "="))
        self.pushButton_14.setText(_translate("calculator", "3"))
        self.pushButton_15.setText(_translate("calculator", "2"))
        self.pushButton_16.setText(_translate("calculator", "1"))








if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    w = QtWidgets.QMainWindow()
    ui = Ui_calculator()
    ui.setupUi(w)
    w.show()
    sys.exit(app.exec_())